{"name": "test_auth_positive", "status": "broken", "statusDetails": {"message": "NameError: name 'chrome_driver_path' is not defined", "trace": "chrome_options = <selenium.webdriver.chrome.options.Options object at 0x0000025E9AE1EC80>\n\n    @pytest.fixture()\n    def driver(chrome_options):\n>       service = Service(chrome_driver_path)\nE       NameError: name 'chrome_driver_path' is not defined\n\nconftest.py:37: NameError"}, "start": 1719407138485, "stop": 1719407138485, "uuid": "99477cf6-2ddf-4791-a1a8-a232998fd3a4", "historyId": "df17cd68b81f863cd337cab7aae82c9c", "testCaseId": "df17cd68b81f863cd337cab7aae82c9c", "fullName": "tests.test_auth#test_auth_positive", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "DESKTOP-7NMG6HA"}, {"name": "thread", "value": "3116-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}